#!/usr/bin/env bash
# sync-doctrine — inline doctrine/*.md into the commands that need it.
#
# WHY THIS EXISTS
# Two constraints collided. (1) Commands must be self-contained: no skill dispatch,
# no "go read that file" — a runtime hop can silently not happen, which is the whole
# reason craft is being rewritten. (2) The same doctrine (TDD, debugging, verification)
# is needed by 2+ commands, and hand-maintained duplicates drift.
#
# `@file` auto-expansion would solve both, but it is not an established pattern for
# plugin COMMANDS — checked across every installed plugin, the only @-reference found
# is prose telling the model to read a file, which is the hop we are removing. So:
# doctrine/*.md is the single source of truth, and this script inlines it between
# markers. Commands stay literally self-contained at runtime; edits happen in one place.
#
# Usage:  sync-doctrine.sh            write the inlined blocks
#         sync-doctrine.sh --check    fail if any command is out of sync (CI gate)
#
# In a command file:
#     <!-- doctrine:tdd:start -->      ...generated, do not edit...    <!-- doctrine:tdd:end -->

set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

changed=0; synced=0; missing=0

# Every command, every doctrine block it declares. Discovered from the markers
# themselves — no second list to keep in step with the first.
for cmd in commands/*.md; do
  [ -f "$cmd" ] || continue

  for name in $(grep -oE '<!-- doctrine:[a-z-]+:start -->' "$cmd" 2>/dev/null \
                | sed 's/<!-- doctrine:\([a-z-]*\):start -->/\1/'); do
    src="doctrine/$name.md"
    if [ ! -f "$src" ]; then
      echo "MISSING  $cmd wants doctrine/$name.md — not found"
      missing=$((missing + 1))
      continue
    fi

    tmp="$(mktemp)"
    awk -v name="$name" -v src="$src" '
      $0 ~ "<!-- doctrine:" name ":start -->" {
        print
        print "<!-- generated by scripts/sync-doctrine.sh — edit " src " instead -->"
        while ((getline l < src) > 0) print l
        close(src)
        skip = 1
        next
      }
      $0 ~ "<!-- doctrine:" name ":end -->" { skip = 0 }
      !skip { print }
    ' "$cmd" > "$tmp"

    if cmp -s "$cmd" "$tmp"; then
      rm -f "$tmp"
      synced=$((synced + 1))
    elif [ "$CHECK" = 1 ]; then
      rm -f "$tmp"
      echo "OUT OF SYNC  $cmd :: $name"
      changed=$((changed + 1))
    else
      mv "$tmp" "$cmd"
      echo "synced  $cmd :: $name"
      changed=$((changed + 1))
    fi
  done
done

if [ "$CHECK" = 1 ]; then
  echo "DOCTRINE-SYNC in-sync=$synced out-of-sync=$changed missing=$missing"
  [ "$changed" -eq 0 ] && [ "$missing" -eq 0 ]
else
  echo "DOCTRINE-SYNC updated=$changed already-current=$synced missing=$missing"
  [ "$missing" -eq 0 ]
fi
